In [1]:
import numpy as np
from tensorflow.keras.layers import Embedding, Flatten, Dense
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [2]:
docs = [ 'additional income',
'best price',
'big bucks',
'cash bonus',
'earn extra cash',
'spring savings certificate',
'valero gas marketing',
'all domestic employees',
'nominations for oct',
'confirmation from spinner']
labeIs = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [8]:
vocab_size = 50
encoded_docs = [one_hot(d, vocab_size) for d in docs]
print(encoded_docs)

[[7, 28], [4, 22], [23, 3], [4, 19], [22, 25, 4], [22, 5, 35], [46, 33, 5], [14, 48, 6], [22, 25, 33], [31, 48, 20]]


In [9]:
max_length = 4
padded_docs = pad_sequences(encoded_docs, maxlen = max_length, padding='post')
print(padded_docs)

[[ 7 28  0  0]
 [ 4 22  0  0]
 [23  3  0  0]
 [ 4 19  0  0]
 [22 25  4  0]
 [22  5 35  0]
 [46 33  5  0]
 [14 48  6  0]
 [22 25 33  0]
 [31 48 20  0]]


In [10]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=max_length))
model.add(Flatten())
model.add(Dense(1, activation= 'sigmoid'))

model.compile(optimizer='adam', loss = 'binary_crossentropy', metrics=['accuracy'])

In [11]:
model.fit(padded_docs, labeIs, epochs=50, verbose=0)

loss, accuracy = model.evaluate(padded_docs,labeIs, verbose=0)
print('정확도=', accuracy)

정확도= 0.8999999761581421


In [12]:
test_doc = ['big income']
encoded_docs = [one_hot(d, vocab_size) for d in test_doc]
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding = 'post')

print(model.predict(padded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
[[0.5873898]]
